include:
  - board: seeeduino_xiao_ble
    shield: Enigma_04_L rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: Enigma_04_L
    
  - board: seeeduino_xiao_ble
    shield: Enigma_04_R rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: Enigma_04_R
    
  - board: seeeduino_xiao_ble
    shield: settings_reset
